### PR TITLE
Brandon dev

### PR DESCRIPTION
**Pull request by brandonjnelsonFDA**
removed conflicted merges, this pr is only additions and trimming down of redundant tests in effort to get the github actions to work

### CODE REVIEW

**Comment by brandonjnelsonFDA** [comment]
While this looks like a lot of commits, most are me fiddling with github actions. Check the files changed and you'll see there are only additions of tests.

You'll like this one, @jmweaver-FDA  because I found a bug, upon fixing it everything runs much faster, i removed unnecessary resizing in the phantoms which made the NIHPD phantoms a large matrix size with no resoltion benefits. Removing this, the NIHPD phantom scans run much faster and MIDA is unchanged.

**Comment by brandonjnelsonFDA** [comment]
Also if you go to the [Github actions tabs](https://github.com/DIDSR/PedSilicoICH/actions/runs/11968040312), test results are saved out and uploaded to github as artifacts so we can visually inspect the results as an integration test

image

**Review by jmweaver-FDA — APPROVED** [review]
Looks great! Especially appreciate the change to speed up NIHPD (especially as we'll be getting back to that data after the first manuscript) as well as the general housekeeping. Kudos as well on getting the tests working :)

**Comment by brandonjnelsonFDA** [comment]
The github actions automatically store the test results enabling us to quickly glance if any changes produce artifacts and that images look as expected for each lesion type:
phantoms.png
phantoms
and images.png
images

**Pull request merged**
